// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_log (store_id, actor_id, action, entity, entity_id, detail)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditLogParams struct {
	StoreID  uuid.UUID   `json:"store_id"`
	ActorID  pgtype.UUID `json:"actor_id"`
	Action   string      `json:"action"`
	Entity   *string     `json:"entity"`
	EntityID pgtype.UUID `json:"entity_id"`
	Detail   []byte      `json:"detail"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.StoreID,
		arg.ActorID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Detail,
	)
	return err
}
