// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bills.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBill = `-- name: CreateBill :one
INSERT INTO bills (
  store_id, bill_no, client_uuid, cashier_id,
  subtotal, discount, total, paid, change,
  payment_method, status, voids_bill_id, synced_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8, $9,
  $10, $11, $12, $13
)
RETURNING id, store_id, bill_no, client_uuid, cashier_id, subtotal, discount, total, paid, change, payment_method, status, voids_bill_id, created_at, synced_at
`

type CreateBillParams struct {
	StoreID       uuid.UUID          `json:"store_id"`
	BillNo        string             `json:"bill_no"`
	ClientUuid    uuid.UUID          `json:"client_uuid"`
	CashierID     pgtype.UUID        `json:"cashier_id"`
	Subtotal      int64              `json:"subtotal"`
	Discount      int64              `json:"discount"`
	Total         int64              `json:"total"`
	Paid          int64              `json:"paid"`
	Change        int64              `json:"change"`
	PaymentMethod string             `json:"payment_method"`
	Status        string             `json:"status"`
	VoidsBillID   pgtype.UUID        `json:"voids_bill_id"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, createBill,
		arg.StoreID,
		arg.BillNo,
		arg.ClientUuid,
		arg.CashierID,
		arg.Subtotal,
		arg.Discount,
		arg.Total,
		arg.Paid,
		arg.Change,
		arg.PaymentMethod,
		arg.Status,
		arg.VoidsBillID,
		arg.SyncedAt,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.BillNo,
		&i.ClientUuid,
		&i.CashierID,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.Paid,
		&i.Change,
		&i.PaymentMethod,
		&i.Status,
		&i.VoidsBillID,
		&i.CreatedAt,
		&i.SyncedAt,
	)
	return i, err
}

const createBillItem = `-- name: CreateBillItem :one
INSERT INTO bill_items (bill_id, product_id, name_snapshot, price_snapshot, qty, line_total)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, bill_id, product_id, name_snapshot, price_snapshot, qty, line_total
`

type CreateBillItemParams struct {
	BillID        uuid.UUID   `json:"bill_id"`
	ProductID     pgtype.UUID `json:"product_id"`
	NameSnapshot  string      `json:"name_snapshot"`
	PriceSnapshot int64       `json:"price_snapshot"`
	Qty           int32       `json:"qty"`
	LineTotal     int64       `json:"line_total"`
}

func (q *Queries) CreateBillItem(ctx context.Context, arg CreateBillItemParams) (BillItem, error) {
	row := q.db.QueryRow(ctx, createBillItem,
		arg.BillID,
		arg.ProductID,
		arg.NameSnapshot,
		arg.PriceSnapshot,
		arg.Qty,
		arg.LineTotal,
	)
	var i BillItem
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.ProductID,
		&i.NameSnapshot,
		&i.PriceSnapshot,
		&i.Qty,
		&i.LineTotal,
	)
	return i, err
}

const getBill = `-- name: GetBill :one
SELECT id, store_id, bill_no, client_uuid, cashier_id, subtotal, discount, total, paid, change, payment_method, status, voids_bill_id, created_at, synced_at FROM bills WHERE id = $1 AND store_id = $2
`

type GetBillParams struct {
	ID      uuid.UUID `json:"id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) GetBill(ctx context.Context, arg GetBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, getBill, arg.ID, arg.StoreID)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.BillNo,
		&i.ClientUuid,
		&i.CashierID,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.Paid,
		&i.Change,
		&i.PaymentMethod,
		&i.Status,
		&i.VoidsBillID,
		&i.CreatedAt,
		&i.SyncedAt,
	)
	return i, err
}

const getBillByClientUUID = `-- name: GetBillByClientUUID :one
SELECT id, store_id, bill_no, client_uuid, cashier_id, subtotal, discount, total, paid, change, payment_method, status, voids_bill_id, created_at, synced_at FROM bills WHERE store_id = $1 AND client_uuid = $2
`

type GetBillByClientUUIDParams struct {
	StoreID    uuid.UUID `json:"store_id"`
	ClientUuid uuid.UUID `json:"client_uuid"`
}

func (q *Queries) GetBillByClientUUID(ctx context.Context, arg GetBillByClientUUIDParams) (Bill, error) {
	row := q.db.QueryRow(ctx, getBillByClientUUID, arg.StoreID, arg.ClientUuid)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.BillNo,
		&i.ClientUuid,
		&i.CashierID,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.Paid,
		&i.Change,
		&i.PaymentMethod,
		&i.Status,
		&i.VoidsBillID,
		&i.CreatedAt,
		&i.SyncedAt,
	)
	return i, err
}

const getVoidForBill = `-- name: GetVoidForBill :one
SELECT id, store_id, bill_no, client_uuid, cashier_id, subtotal, discount, total, paid, change, payment_method, status, voids_bill_id, created_at, synced_at FROM bills WHERE store_id = $1 AND voids_bill_id = $2 LIMIT 1
`

type GetVoidForBillParams struct {
	StoreID     uuid.UUID   `json:"store_id"`
	VoidsBillID pgtype.UUID `json:"voids_bill_id"`
}

func (q *Queries) GetVoidForBill(ctx context.Context, arg GetVoidForBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, getVoidForBill, arg.StoreID, arg.VoidsBillID)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.BillNo,
		&i.ClientUuid,
		&i.CashierID,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.Paid,
		&i.Change,
		&i.PaymentMethod,
		&i.Status,
		&i.VoidsBillID,
		&i.CreatedAt,
		&i.SyncedAt,
	)
	return i, err
}

const listBillItems = `-- name: ListBillItems :many
SELECT id, bill_id, product_id, name_snapshot, price_snapshot, qty, line_total FROM bill_items WHERE bill_id = $1 ORDER BY id
`

func (q *Queries) ListBillItems(ctx context.Context, billID uuid.UUID) ([]BillItem, error) {
	rows, err := q.db.Query(ctx, listBillItems, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillItem{}
	for rows.Next() {
		var i BillItem
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.ProductID,
			&i.NameSnapshot,
			&i.PriceSnapshot,
			&i.Qty,
			&i.LineTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBillSeq = `-- name: NextBillSeq :one
INSERT INTO bill_counters (store_id, next_seq)
VALUES ($1, 2)
ON CONFLICT (store_id) DO UPDATE SET next_seq = bill_counters.next_seq + 1
RETURNING next_seq - 1 AS seq
`

// Atomically allocate the next gap-free sequence for a store. Running inside the
// sale transaction means a rollback also rolls back the increment → no gaps.
func (q *Queries) NextBillSeq(ctx context.Context, storeID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextBillSeq, storeID)
	var seq int32
	err := row.Scan(&seq)
	return seq, err
}
