// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addInventoryQty = `-- name: AddInventoryQty :one
UPDATE inventory
SET qty_on_hand = qty_on_hand + $2
WHERE product_id = $1
RETURNING product_id, store_id, qty_on_hand, reorder_point, updated_at
`

type AddInventoryQtyParams struct {
	ProductID uuid.UUID `json:"product_id"`
	QtyOnHand int32     `json:"qty_on_hand"`
}

// Applies a delta to the cached on-hand (source of truth is stock_movements).
func (q *Queries) AddInventoryQty(ctx context.Context, arg AddInventoryQtyParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, addInventoryQty, arg.ProductID, arg.QtyOnHand)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.StoreID,
		&i.QtyOnHand,
		&i.ReorderPoint,
		&i.UpdatedAt,
	)
	return i, err
}

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventory (product_id, store_id, qty_on_hand, reorder_point)
VALUES ($1, $2, $3, $4)
RETURNING product_id, store_id, qty_on_hand, reorder_point, updated_at
`

type CreateInventoryParams struct {
	ProductID    uuid.UUID `json:"product_id"`
	StoreID      uuid.UUID `json:"store_id"`
	QtyOnHand    int32     `json:"qty_on_hand"`
	ReorderPoint int32     `json:"reorder_point"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory,
		arg.ProductID,
		arg.StoreID,
		arg.QtyOnHand,
		arg.ReorderPoint,
	)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.StoreID,
		&i.QtyOnHand,
		&i.ReorderPoint,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventory = `-- name: GetInventory :one
SELECT product_id, store_id, qty_on_hand, reorder_point, updated_at FROM inventory WHERE product_id = $1
`

func (q *Queries) GetInventory(ctx context.Context, productID uuid.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventory, productID)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.StoreID,
		&i.QtyOnHand,
		&i.ReorderPoint,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryForUpdate = `-- name: GetInventoryForUpdate :one
SELECT product_id, store_id, qty_on_hand, reorder_point, updated_at FROM inventory WHERE product_id = $1 FOR UPDATE
`

// Locks the row so a concurrent sale of the same product can't oversell.
func (q *Queries) GetInventoryForUpdate(ctx context.Context, productID uuid.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryForUpdate, productID)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.StoreID,
		&i.QtyOnHand,
		&i.ReorderPoint,
		&i.UpdatedAt,
	)
	return i, err
}

const setReorderPoint = `-- name: SetReorderPoint :exec
UPDATE inventory SET reorder_point = $2 WHERE product_id = $1
`

type SetReorderPointParams struct {
	ProductID    uuid.UUID `json:"product_id"`
	ReorderPoint int32     `json:"reorder_point"`
}

func (q *Queries) SetReorderPoint(ctx context.Context, arg SetReorderPointParams) error {
	_, err := q.db.Exec(ctx, setReorderPoint, arg.ProductID, arg.ReorderPoint)
	return err
}
