// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        uuid.UUID          `json:"id"`
	StoreID   uuid.UUID          `json:"store_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Action    string             `json:"action"`
	Entity    *string            `json:"entity"`
	EntityID  pgtype.UUID        `json:"entity_id"`
	Detail    []byte             `json:"detail"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Bill struct {
	ID            uuid.UUID          `json:"id"`
	StoreID       uuid.UUID          `json:"store_id"`
	BillNo        string             `json:"bill_no"`
	ClientUuid    uuid.UUID          `json:"client_uuid"`
	CashierID     pgtype.UUID        `json:"cashier_id"`
	Subtotal      int64              `json:"subtotal"`
	Discount      int64              `json:"discount"`
	Total         int64              `json:"total"`
	Paid          int64              `json:"paid"`
	Change        int64              `json:"change"`
	PaymentMethod string             `json:"payment_method"`
	Status        string             `json:"status"`
	VoidsBillID   pgtype.UUID        `json:"voids_bill_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
}

type BillCounter struct {
	StoreID uuid.UUID `json:"store_id"`
	NextSeq int64     `json:"next_seq"`
}

type BillItem struct {
	ID            uuid.UUID   `json:"id"`
	BillID        uuid.UUID   `json:"bill_id"`
	ProductID     pgtype.UUID `json:"product_id"`
	NameSnapshot  string      `json:"name_snapshot"`
	PriceSnapshot int64       `json:"price_snapshot"`
	Qty           int32       `json:"qty"`
	LineTotal     int64       `json:"line_total"`
}

type Inventory struct {
	ProductID    uuid.UUID          `json:"product_id"`
	StoreID      uuid.UUID          `json:"store_id"`
	QtyOnHand    int32              `json:"qty_on_hand"`
	ReorderPoint int32              `json:"reorder_point"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID        uuid.UUID          `json:"id"`
	StoreID   uuid.UUID          `json:"store_id"`
	Name      string             `json:"name"`
	Barcode   *string            `json:"barcode"`
	Category  string             `json:"category"`
	CostPrice int64              `json:"cost_price"`
	SellPrice int64              `json:"sell_price"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	StoreID    uuid.UUID          `json:"store_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type StockMovement struct {
	ID         uuid.UUID          `json:"id"`
	StoreID    uuid.UUID          `json:"store_id"`
	ProductID  uuid.UUID          `json:"product_id"`
	Type       string             `json:"type"`
	QtyDelta   int32              `json:"qty_delta"`
	RefType    *string            `json:"ref_type"`
	RefID      pgtype.UUID        `json:"ref_id"`
	Reason     *string            `json:"reason"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	ClientUuid pgtype.UUID        `json:"client_uuid"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Store struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Config    []byte             `json:"config"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SyncLog struct {
	ID        uuid.UUID          `json:"id"`
	StoreID   uuid.UUID          `json:"store_id"`
	DeviceID  *string            `json:"device_id"`
	OpsCount  int32              `json:"ops_count"`
	Conflicts int32              `json:"conflicts"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	StoreID      uuid.UUID          `json:"store_id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	PinHash      *string            `json:"pin_hash"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
