// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPayment = `-- name: CancelPayment :exec
UPDATE payments SET status = 'cancelled'
WHERE id = $1 AND store_id = $2 AND status = 'pending'
`

type CancelPaymentParams struct {
	ID      uuid.UUID `json:"id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) CancelPayment(ctx context.Context, arg CancelPaymentParams) error {
	_, err := q.db.Exec(ctx, cancelPayment, arg.ID, arg.StoreID)
	return err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (store_id, bill_client_uuid, amount, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, store_id, bill_client_uuid, amount, status, ref, raw_note, created_at, paid_at, expires_at
`

type CreatePaymentParams struct {
	StoreID        uuid.UUID          `json:"store_id"`
	BillClientUuid pgtype.UUID        `json:"bill_client_uuid"`
	Amount         int64              `json:"amount"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.StoreID,
		arg.BillClientUuid,
		arg.Amount,
		arg.ExpiresAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.BillClientUuid,
		&i.Amount,
		&i.Status,
		&i.Ref,
		&i.RawNote,
		&i.CreatedAt,
		&i.PaidAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, store_id, bill_client_uuid, amount, status, ref, raw_note, created_at, paid_at, expires_at FROM payments WHERE id = $1 AND store_id = $2
`

type GetPaymentParams struct {
	ID      uuid.UUID `json:"id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, arg.ID, arg.StoreID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.BillClientUuid,
		&i.Amount,
		&i.Status,
		&i.Ref,
		&i.RawNote,
		&i.CreatedAt,
		&i.PaidAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markPaymentPaid = `-- name: MarkPaymentPaid :exec
UPDATE payments
SET status = 'paid', paid_at = now(), ref = $2, raw_note = $3
WHERE id = $1
`

type MarkPaymentPaidParams struct {
	ID      uuid.UUID `json:"id"`
	Ref     *string   `json:"ref"`
	RawNote *string   `json:"raw_note"`
}

func (q *Queries) MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) error {
	_, err := q.db.Exec(ctx, markPaymentPaid, arg.ID, arg.Ref, arg.RawNote)
	return err
}

const matchPendingPaymentForUpdate = `-- name: MatchPendingPaymentForUpdate :one
SELECT id, store_id, bill_client_uuid, amount, status, ref, raw_note, created_at, paid_at, expires_at FROM payments
WHERE status = 'pending' AND amount = $1 AND expires_at > now()
ORDER BY created_at
LIMIT 1
FOR UPDATE SKIP LOCKED
`

// Oldest pending intent for this exact amount that hasn't expired.
func (q *Queries) MatchPendingPaymentForUpdate(ctx context.Context, amount int64) (Payment, error) {
	row := q.db.QueryRow(ctx, matchPendingPaymentForUpdate, amount)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.BillClientUuid,
		&i.Amount,
		&i.Status,
		&i.Ref,
		&i.RawNote,
		&i.CreatedAt,
		&i.PaidAt,
		&i.ExpiresAt,
	)
	return i, err
}
