// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (store_id, name, barcode, category, cost_price, sell_price)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, store_id, name, barcode, category, cost_price, sell_price, is_active, created_at, updated_at
`

type CreateProductParams struct {
	StoreID   uuid.UUID `json:"store_id"`
	Name      string    `json:"name"`
	Barcode   *string   `json:"barcode"`
	Category  string    `json:"category"`
	CostPrice int64     `json:"cost_price"`
	SellPrice int64     `json:"sell_price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.StoreID,
		arg.Name,
		arg.Barcode,
		arg.Category,
		arg.CostPrice,
		arg.SellPrice,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Barcode,
		&i.Category,
		&i.CostPrice,
		&i.SellPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateProduct = `-- name: DeactivateProduct :execrows
UPDATE products SET is_active = FALSE
WHERE id = $1 AND store_id = $2
`

type DeactivateProductParams struct {
	ID      uuid.UUID `json:"id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) DeactivateProduct(ctx context.Context, arg DeactivateProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateProduct, arg.ID, arg.StoreID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, store_id, name, barcode, category, cost_price, sell_price, is_active, created_at, updated_at FROM products WHERE id = $1 AND store_id = $2
`

type GetProductParams struct {
	ID      uuid.UUID `json:"id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.ID, arg.StoreID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Barcode,
		&i.Category,
		&i.CostPrice,
		&i.SellPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByBarcode = `-- name: GetProductByBarcode :one
SELECT id, store_id, name, barcode, category, cost_price, sell_price, is_active, created_at, updated_at FROM products
WHERE store_id = $1 AND barcode = $2 AND is_active = TRUE
`

type GetProductByBarcodeParams struct {
	StoreID uuid.UUID `json:"store_id"`
	Barcode *string   `json:"barcode"`
}

func (q *Queries) GetProductByBarcode(ctx context.Context, arg GetProductByBarcodeParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByBarcode, arg.StoreID, arg.Barcode)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Barcode,
		&i.Category,
		&i.CostPrice,
		&i.SellPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductsWithStock = `-- name: ListProductsWithStock :many
SELECT
  p.id, p.store_id, p.name, p.barcode, p.category, p.cost_price, p.sell_price, p.is_active, p.created_at, p.updated_at,
  COALESCE(i.qty_on_hand, 0)::int   AS qty_on_hand,
  COALESCE(i.reorder_point, 0)::int AS reorder_point
FROM products p
LEFT JOIN inventory i ON i.product_id = p.id
WHERE p.store_id = $1 AND p.is_active = TRUE
ORDER BY p.name
`

type ListProductsWithStockRow struct {
	ID           uuid.UUID          `json:"id"`
	StoreID      uuid.UUID          `json:"store_id"`
	Name         string             `json:"name"`
	Barcode      *string            `json:"barcode"`
	Category     string             `json:"category"`
	CostPrice    int64              `json:"cost_price"`
	SellPrice    int64              `json:"sell_price"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	QtyOnHand    int32              `json:"qty_on_hand"`
	ReorderPoint int32              `json:"reorder_point"`
}

func (q *Queries) ListProductsWithStock(ctx context.Context, storeID uuid.UUID) ([]ListProductsWithStockRow, error) {
	rows, err := q.db.Query(ctx, listProductsWithStock, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsWithStockRow{}
	for rows.Next() {
		var i ListProductsWithStockRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.Barcode,
			&i.Category,
			&i.CostPrice,
			&i.SellPrice,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QtyOnHand,
			&i.ReorderPoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $3, barcode = $4, category = $5, cost_price = $6, sell_price = $7
WHERE id = $1 AND store_id = $2
RETURNING id, store_id, name, barcode, category, cost_price, sell_price, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	ID        uuid.UUID `json:"id"`
	StoreID   uuid.UUID `json:"store_id"`
	Name      string    `json:"name"`
	Barcode   *string   `json:"barcode"`
	Category  string    `json:"category"`
	CostPrice int64     `json:"cost_price"`
	SellPrice int64     `json:"sell_price"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.StoreID,
		arg.Name,
		arg.Barcode,
		arg.Category,
		arg.CostPrice,
		arg.SellPrice,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Barcode,
		&i.Category,
		&i.CostPrice,
		&i.SellPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
