// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Applies a delta to the cached on-hand (source of truth is stock_movements).
	AddInventoryQty(ctx context.Context, arg AddInventoryQtyParams) (Inventory, error)
	CancelPayment(ctx context.Context, arg CancelPaymentParams) error
	CountUsersInStore(ctx context.Context, storeID uuid.UUID) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error)
	CreateBillItem(ctx context.Context, arg CreateBillItemParams) (BillItem, error)
	CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error)
	CreateMovement(ctx context.Context, arg CreateMovementParams) (StockMovement, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DailySales(ctx context.Context, arg DailySalesParams) ([]DailySalesRow, error)
	DeactivateProduct(ctx context.Context, arg DeactivateProductParams) (int64, error)
	// Single-tenant login: username resolves to one active user. When true
	// multi-tenant login lands, add store scoping / a store selector here.
	GetActiveUserByUsername(ctx context.Context, username string) (User, error)
	GetBill(ctx context.Context, arg GetBillParams) (Bill, error)
	GetBillByClientUUID(ctx context.Context, arg GetBillByClientUUIDParams) (Bill, error)
	GetInventory(ctx context.Context, productID uuid.UUID) (Inventory, error)
	// Locks the row so a concurrent sale of the same product can't oversell.
	GetInventoryForUpdate(ctx context.Context, productID uuid.UUID) (Inventory, error)
	GetMovementByClientUUID(ctx context.Context, arg GetMovementByClientUUIDParams) (StockMovement, error)
	GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error)
	GetProduct(ctx context.Context, arg GetProductParams) (Product, error)
	GetProductByBarcode(ctx context.Context, arg GetProductByBarcodeParams) (Product, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetStore(ctx context.Context, id uuid.UUID) (Store, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetVoidForBill(ctx context.Context, arg GetVoidForBillParams) (Bill, error)
	ListBillItems(ctx context.Context, billID uuid.UUID) ([]BillItem, error)
	ListMovementsByProduct(ctx context.Context, arg ListMovementsByProductParams) ([]StockMovement, error)
	ListProductsWithStock(ctx context.Context, storeID uuid.UUID) ([]ListProductsWithStockRow, error)
	ListStores(ctx context.Context) ([]Store, error)
	LowStockCount(ctx context.Context, storeID uuid.UUID) (int64, error)
	MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) error
	// Oldest pending intent for this exact amount that hasn't expired.
	MatchPendingPaymentForUpdate(ctx context.Context, amount int64) (Payment, error)
	// Atomically allocate the next gap-free sequence for a store. Running inside the
	// sale transaction means a rollback also rolls back the increment → no gaps.
	NextBillSeq(ctx context.Context, storeID uuid.UUID) (int32, error)
	// Authoritative on-hand = sum of the immutable ledger.
	OnHandFromLedger(ctx context.Context, productID uuid.UUID) (int64, error)
	ProfitApprox(ctx context.Context, arg ProfitApproxParams) (int64, error)
	RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	// Reports exclude voided sales: a completed bill counts only if no void bill
	// references it. Profit is approximate (uses current product cost).
	SalesTotals(ctx context.Context, arg SalesTotalsParams) (SalesTotalsRow, error)
	SetReorderPoint(ctx context.Context, arg SetReorderPointParams) error
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	TopProducts(ctx context.Context, arg TopProductsParams) ([]TopProductsRow, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
