// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const dailySales = `-- name: DailySales :many
SELECT
  (b.created_at AT TIME ZONE 'Asia/Bangkok')::date AS day,
  COALESCE(SUM(b.total), 0)::bigint                AS sales
FROM bills b
WHERE b.store_id = $1 AND b.status = 'completed' AND b.created_at >= $2
  AND NOT EXISTS (SELECT 1 FROM bills v WHERE v.voids_bill_id = b.id AND v.status = 'void')
GROUP BY day
ORDER BY day
`

type DailySalesParams struct {
	StoreID   uuid.UUID          `json:"store_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DailySalesRow struct {
	Day   pgtype.Date `json:"day"`
	Sales int64       `json:"sales"`
}

func (q *Queries) DailySales(ctx context.Context, arg DailySalesParams) ([]DailySalesRow, error) {
	rows, err := q.db.Query(ctx, dailySales, arg.StoreID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailySalesRow{}
	for rows.Next() {
		var i DailySalesRow
		if err := rows.Scan(&i.Day, &i.Sales); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lowStockCount = `-- name: LowStockCount :one
SELECT COUNT(*)::bigint AS low
FROM inventory
WHERE store_id = $1 AND qty_on_hand <= reorder_point
`

func (q *Queries) LowStockCount(ctx context.Context, storeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, lowStockCount, storeID)
	var low int64
	err := row.Scan(&low)
	return low, err
}

const profitApprox = `-- name: ProfitApprox :one
SELECT COALESCE(SUM(bi.line_total - bi.qty * p.cost_price), 0)::bigint AS profit
FROM bills b
JOIN bill_items bi ON bi.bill_id = b.id
JOIN products p    ON p.id = bi.product_id
WHERE b.store_id = $1 AND b.status = 'completed'
  AND b.created_at >= $2 AND b.created_at < $3
  AND NOT EXISTS (SELECT 1 FROM bills v WHERE v.voids_bill_id = b.id AND v.status = 'void')
`

type ProfitApproxParams struct {
	StoreID     uuid.UUID          `json:"store_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) ProfitApprox(ctx context.Context, arg ProfitApproxParams) (int64, error) {
	row := q.db.QueryRow(ctx, profitApprox, arg.StoreID, arg.CreatedAt, arg.CreatedAt_2)
	var profit int64
	err := row.Scan(&profit)
	return profit, err
}

const salesTotals = `-- name: SalesTotals :one

SELECT
  COALESCE(SUM(total), 0)::bigint AS sales,
  COUNT(*)::bigint               AS bills
FROM bills b
WHERE b.store_id = $1 AND b.status = 'completed'
  AND b.created_at >= $2 AND b.created_at < $3
  AND NOT EXISTS (SELECT 1 FROM bills v WHERE v.voids_bill_id = b.id AND v.status = 'void')
`

type SalesTotalsParams struct {
	StoreID     uuid.UUID          `json:"store_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type SalesTotalsRow struct {
	Sales int64 `json:"sales"`
	Bills int64 `json:"bills"`
}

// Reports exclude voided sales: a completed bill counts only if no void bill
// references it. Profit is approximate (uses current product cost).
func (q *Queries) SalesTotals(ctx context.Context, arg SalesTotalsParams) (SalesTotalsRow, error) {
	row := q.db.QueryRow(ctx, salesTotals, arg.StoreID, arg.CreatedAt, arg.CreatedAt_2)
	var i SalesTotalsRow
	err := row.Scan(&i.Sales, &i.Bills)
	return i, err
}

const topProducts = `-- name: TopProducts :many
SELECT p.id, p.name, COALESCE(SUM(-sm.qty_delta), 0)::bigint AS qty_sold
FROM products p
JOIN stock_movements sm ON sm.product_id = p.id AND sm.type = 'sale'
WHERE p.store_id = $1
GROUP BY p.id, p.name
ORDER BY qty_sold DESC
LIMIT $2
`

type TopProductsParams struct {
	StoreID uuid.UUID `json:"store_id"`
	Limit   int32     `json:"limit"`
}

type TopProductsRow struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	QtySold int64     `json:"qty_sold"`
}

func (q *Queries) TopProducts(ctx context.Context, arg TopProductsParams) ([]TopProductsRow, error) {
	rows, err := q.db.Query(ctx, topProducts, arg.StoreID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopProductsRow{}
	for rows.Next() {
		var i TopProductsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.QtySold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
