// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_movements.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMovement = `-- name: CreateMovement :one
INSERT INTO stock_movements
  (store_id, product_id, type, qty_delta, ref_type, ref_id, reason, created_by, client_uuid)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, store_id, product_id, type, qty_delta, ref_type, ref_id, reason, created_by, client_uuid, created_at
`

type CreateMovementParams struct {
	StoreID    uuid.UUID   `json:"store_id"`
	ProductID  uuid.UUID   `json:"product_id"`
	Type       string      `json:"type"`
	QtyDelta   int32       `json:"qty_delta"`
	RefType    *string     `json:"ref_type"`
	RefID      pgtype.UUID `json:"ref_id"`
	Reason     *string     `json:"reason"`
	CreatedBy  pgtype.UUID `json:"created_by"`
	ClientUuid pgtype.UUID `json:"client_uuid"`
}

func (q *Queries) CreateMovement(ctx context.Context, arg CreateMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, createMovement,
		arg.StoreID,
		arg.ProductID,
		arg.Type,
		arg.QtyDelta,
		arg.RefType,
		arg.RefID,
		arg.Reason,
		arg.CreatedBy,
		arg.ClientUuid,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.ProductID,
		&i.Type,
		&i.QtyDelta,
		&i.RefType,
		&i.RefID,
		&i.Reason,
		&i.CreatedBy,
		&i.ClientUuid,
		&i.CreatedAt,
	)
	return i, err
}

const getMovementByClientUUID = `-- name: GetMovementByClientUUID :one
SELECT id, store_id, product_id, type, qty_delta, ref_type, ref_id, reason, created_by, client_uuid, created_at FROM stock_movements
WHERE store_id = $1 AND client_uuid = $2
`

type GetMovementByClientUUIDParams struct {
	StoreID    uuid.UUID   `json:"store_id"`
	ClientUuid pgtype.UUID `json:"client_uuid"`
}

func (q *Queries) GetMovementByClientUUID(ctx context.Context, arg GetMovementByClientUUIDParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, getMovementByClientUUID, arg.StoreID, arg.ClientUuid)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.ProductID,
		&i.Type,
		&i.QtyDelta,
		&i.RefType,
		&i.RefID,
		&i.Reason,
		&i.CreatedBy,
		&i.ClientUuid,
		&i.CreatedAt,
	)
	return i, err
}

const listMovementsByProduct = `-- name: ListMovementsByProduct :many
SELECT id, store_id, product_id, type, qty_delta, ref_type, ref_id, reason, created_by, client_uuid, created_at FROM stock_movements
WHERE store_id = $1 AND product_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListMovementsByProductParams struct {
	StoreID   uuid.UUID `json:"store_id"`
	ProductID uuid.UUID `json:"product_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListMovementsByProduct(ctx context.Context, arg ListMovementsByProductParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listMovementsByProduct, arg.StoreID, arg.ProductID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockMovement{}
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.ProductID,
			&i.Type,
			&i.QtyDelta,
			&i.RefType,
			&i.RefID,
			&i.Reason,
			&i.CreatedBy,
			&i.ClientUuid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const onHandFromLedger = `-- name: OnHandFromLedger :one
SELECT COALESCE(SUM(qty_delta), 0)::bigint AS on_hand
FROM stock_movements
WHERE product_id = $1
`

// Authoritative on-hand = sum of the immutable ledger.
func (q *Queries) OnHandFromLedger(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, onHandFromLedger, productID)
	var on_hand int64
	err := row.Scan(&on_hand)
	return on_hand, err
}
