// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countUsersInStore = `-- name: CountUsersInStore :one
SELECT count(*) FROM users WHERE store_id = $1
`

func (q *Queries) CountUsersInStore(ctx context.Context, storeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersInStore, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (store_id, username, password_hash, role, pin_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, store_id, username, password_hash, role, pin_hash, is_active, created_at, updated_at
`

type CreateUserParams struct {
	StoreID      uuid.UUID `json:"store_id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	PinHash      *string   `json:"pin_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.StoreID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.PinHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.PinHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveUserByUsername = `-- name: GetActiveUserByUsername :one
SELECT id, store_id, username, password_hash, role, pin_hash, is_active, created_at, updated_at FROM users
WHERE username = $1 AND is_active = TRUE
LIMIT 1
`

// Single-tenant login: username resolves to one active user. When true
// multi-tenant login lands, add store scoping / a store selector here.
func (q *Queries) GetActiveUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.PinHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, store_id, username, password_hash, role, pin_hash, is_active, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.PinHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET is_active = $2 WHERE id = $1
`

type SetUserActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.ID, arg.IsActive)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
